/leveltop can now have a limit set
Bibliofile/BHMB-Quests pull request #2
Opened 2019-10-29 07:21 UTC by WillQi

Completes #1

2019-10-29 17:03 UTC, Bibliofile requested changes

2019-10-29 17:03 UTC, Bibliofile commented on src/info-tab.ts
> +    levelTopElement.setAttribute('value', getLeaderboardLimit(ex).toString())
Is there a reason you don't just use `levelTopElement.value = getLeaderboardLimit(ex).toString()`?

2019-10-29 22:59 UTC, WillQi commented on src/info-tab.ts
> +    levelTopElement.setAttribute('value', getLeaderboardLimit(ex).toString())
Not really, sorry about that!
Changed!

2019-10-30 02:07 UTC, merged

2019-10-30 02:07 UTC, Bibliofile commented
Thanks!